version: "3.9"  # optional since v1.27.0
services:
  hobos-client:
    image: dd1331/hobos-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'